### ISSUE TITLE
entity issue

### ISSUE THREAD

**Issue by carat-jhcha** [pgvector/pgvector-java#15]
```
    @Column(name = "embedding")
    @JdbcTypeCode(SqlTypes.VECTOR)
    @Array(length = 1536)
    var embedding: FloatArray? = null
```

when i try this code, it throw error below

could not deserialize; nested exception is org.hibernate.type.SerializationException: could not deserialize

how can i mapping entity properly in kotlin spring boot?

**Comment by ankane** [comment]
Hi @carat-jhcha, please report Hibernate issues to Hibernate.
