### ISSUE TITLE
Support Java versions prior to Java 19

### ISSUE THREAD

**Issue by ccjernigan** [pgvector/pgvector-java#2]
Trying to use the pgvector 0.1.1 library with Java 17 results in the following error:

`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/pgvector/PGvector has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0`

It appears that pgvector is being compiled with Java 19.  It would be great for pgvector to support older Java versions.  At a minimum, supporting the most recent LTS version of Java would be helpful.

**Comment by ankane** [comment]
Hi @ccjernigan, thanks for reporting! Just pushed 0.1.2, which was built with Java 11 (class file version 53). Also added Java 11 and 17 to CI.

**Comment by davecramer** [comment]
probably worth doing java 8 as well it's pretty prevalent.
