### ISSUE TITLE
release Java 8

### ISSUE THREAD

**Issue by davecramer** [pgvector/pgvector-java#6]
Java 8 is surprisingly prevalent. 
There's no real need for a JAVA 11 or 17 jar, JAVA 8 can be used for all of them, unless of course you have some code that is dependent on 11, or 17, which from what I can tell you do not.
pgjdbc releases with JAVA 8

**Comment by ankane** [comment]
Hi @davecramer, thanks for the suggestion. Just pushed 0.1.3, which supports Java 8.
