### ISSUE TITLE
PSQLException: ERROR: operator does not exist: vector <-> bytea

### ISSUE THREAD

**Issue by jaspart** [pgvector/pgvector-java#7]
Hello,
I tried to use `com.pgvector.PGvector` as follow:
in my service, I get the embedding and put it in a `PGvector(float[])`:
```
      embedding = ArrayUtils.toPrimitive(response.getObject().getJSONArray("text_embedding").toList()
        .stream().map(o -> ((BigDecimal) o).floatValue())
        .collect(Collectors.toList()).toArray(new Float[0]));

return new PGvector(embedding);
```

in the repository layer, I send the request:
```
  @Query(value = "SELECT * FROM my_object ORDER BY embedding <-> :vector LIMIT 3", nativeQuery = true)
  @NotNull List<MyObject> findTopMatchingByVector (@Param("vector") PGvector vector);
```

But I get:
```
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: vector <-> bytea
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
```

Any idea?
Thanks in advance
Arnaud

**Comment by ankane** [comment]
Hi @jaspart, it looks like passing pgJDBC types directly isn't supported. You should be able to pass the vector as a `String` with `vector.getValue()` and cast in the query with `embedding <-> CAST(:vector AS vector)`.

**Comment by jaspart** [comment]
Fixed, thank you.

**Comment by ankane** [comment]
Great. It should be possible to add a `UserType` for Hibernate, so may do that in the future (#1).
